### PR TITLE
Deployment

### PR DESCRIPTION
**Pull request by hugoxiong5**
deployable version with env variables

### CODE REVIEW

**Review by ushift-d — COMMENTED** [review]
Added new relic script

**Review by ushift-d — COMMENTED** [review]
looks like a git ignore

**Review by ushift-d — COMMENTED** [review]
Another git ignore situation

**Review by ushift-d — COMMENTED** [review]
If you git ignored the seeding script I'm not sure need to unless it has sensitive information or its the csv that are generated

**Review by ushift-d — COMMENTED** [review]
This is good practice for changing keys

**Review by ushift-d — COMMENTED** [review]
It doesn't show many changes here just naming changes and addition of delimitators, did you happen to add another table?

**Review by ushift-d — COMMENTED** [review]
If its a non-number won't your table handle the error though this might be better because you won't have to go into your db at all. Another option is if you have the 10 mill limit and providing that as the guidelines for the search. But this is scalable for new records.

**Review by ushift-d — COMMENTED** [review]
Added a randomize for you k6. The seed range portion is change in comments.

**Review by ushift-d — COMMENTED** [review]
Threshold scenarios, I actually should probably use these for my own sake as well. This is pretty good.  Past the prereq requirements.

**Review by ushift-d — COMMENTED** [review]
Redis caching added.

**Comment by ushift-d** [comment]
Looks good to me! Sorry for the late review.

**Comment by hugoxiong5** [comment]
> Looks good to me! Sorry for the late review.

Thanks a bunch! Helpful comments. For some reason I can't see the code your code is referring to, so I'm not sure how to answer some of your questions. I didn't add another table. Not sure what you meant by "if it is a non-number."

**Pull request merged**
